export default {
    files: ['src/**/*.{ts,tsx,*.ts,*tsx}'],
    ignores: ['node_modules/**/*', 'build/**/*'],
    linterOptions: {
        reportUnusedDisableDirectives: 'error',
    },
    rules: {
        'unicorn/import-index': 'off',
        '@typescript-eslint/ban-ts-comment': 'off',
        'no-await-in-loop': 'off',
        'prettier/prettier': [
            'error',
            {
                endOfLine: 'auto',
            },
        ],
        'no-shadow': 'off',
        'no-void': 'off',
        'linebreak-style': 'off',

        'no-undef': 'warn',

        camelcase: ['error'],
        'eol-last': ['error'],
        'object-curly-spacing': ['error', 'always'],
        curly: ['error'],
        'for-direction': ['error'],
        eqeqeq: ['error', 'always', { null: 'ignore' }],
        'use-isnan': ['error'],
        'arrow-parens': ['error'],
        'no-else-return': ['error'],
        'valid-typeof': ['error'],
        'object-shorthand': ['error'],
        'prefer-arrow-callback': ['error'],
        'prefer-const': ['error'],
        'prefer-destructuring': ['error'],
        'prefer-template': ['error'],
        'no-empty': ['error'],
        'no-var': ['error'],
        'no-array-constructor': ['error'],
        'no-lonely-if': ['error'],
        'no-multiple-empty-lines': ['error'],
        'no-extra-boolean-cast': ['error'],
        'no-empty-pattern': ['error'],
        'no-fallthrough': ['error'],
        'no-implicit-coercion': ['error'],
        'no-return-await': ['error'],
        'no-self-assign': ['error'],
        'no-useless-catch': ['error'],
        'no-useless-escape': ['error'],
        'require-await': ['error'],
        'no-extra-semi': ['error'],
        'no-promise-executor-return': ['error'],
        'no-unreachable': ['error'],
        'no-unreachable-loop': ['error'],
        'no-unsafe-negation': ['error'],
        'no-async-promise-executor': ['error'],
        'no-dupe-args': ['error'],
        'no-dupe-keys': ['error'],
        'no-duplicate-case': ['error'],
        'no-dupe-else-if': ['error'],
        'arrow-body-style': ['error', 'as-needed'],
        'padding-line-between-statements': [
            'error',
            { blankLine: 'never', prev: 'import', next: 'import' },
            { blankLine: 'always', prev: '*', next: ['return', 'function', 'if', 'export', 'switch'] },
            { blankLine: 'always', prev: ['if', 'switch'], next: '*' },
            { blankLine: 'always', prev: ['const', 'let'], next: 'expression' },
        ],
    },
};
